version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres-go
    environment:
      POSTGRES_DB: marketdb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d marketdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  kafka:
    image: apache/kafka:latest
    container_name: kafka-go
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CLUSTER_ID: 4YjUOeEaQzq1r5t6v7w8x9
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    volumes:
      - kafka_data:/var/lib/kafka

  redis:
    image: redis:7-alpine
    container_name: redis-rating
    ports:
      - "6379:6379"
    restart: unless-stopped


  migrate:
    image: migrate/migrate
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations
    command:
      [
        "-path", "/migrations",
        "-database",
        "postgres://root:root@postgres:5432/marketdb?sslmode=disable",
        "up"
      ]

  seed:
    build:
      context: ./services/reviews
      dockerfile: tools/seed/Dockerfile
    environment:
      DATABASE_DSN: postgres://root:root@postgres:5432/marketdb?sslmode=disable
    depends_on:
      migrate:
        condition: service_completed_successfully

  reviews:
    build:
      context: ./services/reviews
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started
      seed:
        condition: service_completed_successfully
    ports:
      - "8081:8081"

  rating:
    build:
      context: ./services/rating
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started
      redis:
        condition: service_started
      seed:
        condition: service_completed_successfully
    ports:
      - "8082:8082"

  recommend:
    build:
      context: ./services/recommend
    depends_on:
      redis:
        condition: service_started
      rating:
        condition: service_started
    ports:
      - "8083:8083"
      
  akhq:
    image: tchiotludo/akhq:latest
    container_name: akhq-go
    depends_on:
      - kafka
    ports:
      - "8555:8080"
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            kafka-docker:
              properties:
                bootstrap.servers: "kafka:9092"

volumes:
  postgres_data:
  kafka_data:
