postgres:
  dsn: "postgres://root:root@postgres:5432/marketdb?sslmode=disable"

kafka:
  brokers:
    - "kafka:9092"
  group_id: "rating-service"
  topic: "recalculation-requests"

redis:
  addr: "redis:6379"

http:
  addr: ":8082"
