postgres:
  dsn: "postgres://root:root@postgres:5432/marketdb"

redis:
  addr: "redis:6379"

kafka:
  brokers:
    - "kafka:9092"
  group_id: "rating-service-group"
  topic: "recalculation-requests"

http:
  addr: ":8082"

migrations:
  path: "migrations"
